- src/hamster/external.py
- src/hamster/preferences.py
Deleting the remote branch closed ticket #170. This is a re-based pull request.
> Add taskwarrior integration

- README.md
As in here http://choorucode.com/2014/10/06/cannot-import-name-gconf-error
> Added gir1.2-gconf-2.0 as dependency (Debian)

- src/hamster/overview.py
This small change fixes bug #245. Not sure if it the best fix but it allows me to use the application again.
> Fix division by zero (#245)

- src/hamster/preferences.py
> Fix TargetFlags

- src/hamster/overview.py
> Workaround to add time spend per tag to the overview, #277

- README.md
> Add python-gi-cairo dependency

- data/edit_activity.ui
- src/hamster/overview.py
Unable to find out how to add the necessary modifications to the PR #302 branch.
Maybe "Allow edits from maintainers" was not checked ?
=> new PR for an easy merge.
> Minor layout fixes (merge CendioOssman PR)

- src/hamster-cli
- src/hamster/client.py
- src/hamster/edit_activity.py
- src/hamster/lib/__init__.py
- src/hamster/overview.py
- src/hamster/reports.py
- src/hamster/widgets/facttree.py
With this PR, selecting a line in the overview, and clicking on the `+` button,
starts a new activity that is a clone of the selected one,
except starting now and running. (solves issues #331 and #279)
It seems to work, but has not been thoroughly tested (feedback welcome).
Better keyboard handling is in progress.
> Start clone

- src/hamster/lib/__init__.py
Otherwise the default date at fact creation would be off after midnight.
> take the current hamster day as default date

- tests/stuff_test.py
> test for decimal number in activity

- src/hamster/storage/db.py
> look for ../../../data/ instead of ../../data/ in src/hamster/storage/db.py

- NEWS
- help/wscript
- src/hamster-cli
- src/hamster/lib/__init__.py
- src/hamster/overview.py
- src/hamster/reports.py
- src/hamster/widgets/activityentry.py
- tests/stuff_test.py
- wafadmin/Tools/gnome.py
These fixes were created while I was working on the openSUSE package lately. Well, I guess the second one is more a feature addition than a bug fix, although I like it a lot. I can create another PR without it if you prefer.
> Fix some install paths, and provide help menu entry

- tests/stuff_test.py
Add more tests, following issue #154
> test spaces between category and tags

- NEWS
- src/hamster-cli
- src/hamster-service
- src/hamster/__init__.py
- src/hamster/external.py
- src/hamster/idle.py
- src/hamster/lib/__init__.py
- src/hamster/lib/configuration.py
- src/hamster/lib/desktop.py
- src/hamster/lib/stuff.py
- src/hamster/storage/db.py
- src/hamster/widgets/activityentry.py
Fix #400, which has acquaintances with #211.
Needed some debugging, so incidentally migrated to `argparse`
to set the debugging level from the command-line.
> Monitor external db changes

- data/edit_activity.ui
Implement @lechndo's  edit_activity.ui.txt file to make the task editing window resizeable.
Closes #295
> Make update activity window resizable

- src/hamster/storage/db.py
> Fix an overlapping activity bug

- help/C/merge.page
Clarify how overlapping activities are split/merged. Refs #396.
> improve docs on merging/splitting activities

- README.md
instructions proposed by Gerald Jansen in #369
> debian instructions link

- help/C/input.page
> Remove warning from help input.page.

- README.md
Put more emphasis on revived development of the hamster sub-project.
> update README to de-emphasize the rewrite

- src/hamster-cli
- src/hamster/about.py
Minor fixes to hamster-cli concerning commands to open windows (refs #463).
Also update the homepage in "About" to point to the github wiki page.
> Fix hamster-cli window calls

- data/edit_activity.ui
- src/hamster-service.py
- src/hamster/storage/db.py
Mainly fix #478,
with small category-related clarifications.
> Fix category changes

- src/hamster-cli.py
> use storage.check_fact in cli

- README.md
Advertise the new snap package (#418).
Distribution packages often bring customized integration, so they come first in the list.
> advertise snap package

- src/hamster/lib/datetime.py
- tests/stuff_test.py
> use DOTALL flag in Range.parse

- src/hamster/lib/datetime.py
- src/hamster/widgets/activityentry.py
- tests/stuff_test.py
The GUI cmdline suggestion "Stop now"  range did not follow the text changes.
Fixed.
> Fix cmdline suggestions

- help/C/index.page
- help/C/input.page
- help/C/keys.page
- help/Makefile.am
This PR starts with the two commits by @GeraldJansen (thanks !) 
from #484 that was unfortunately closed, and could not be reopened.
And few modifications (title, new time input capabilities).
> Shortcuts help

- src/hamster/storage/db.py
Minor tweak from fact.name to fact.activity.
> Fix search function (#551)

- README.md
> Update README with comment concerning Development

- src/hamster/lib/graphics.py
Fix #571.
Rationale: https://github.com/projecthamster/hamster/issues/571#issuecomment-591569158.
> Store _window as soon as possible

- MAINTAINERS
rationale: https://github.com/projecthamster/hamster/issues/574#issuecomment-593156136
> remove ederag from maintainers

- README.md
- src/hamster/lib/datetime.py
- src/hamster/lib/fact.py
This PR makes some small changes to support Python3.5 again. It should not change behaviour in any way.
> Support python 3.5

- .bumpversion.cfg
- NEWS.md
- src/hamster/__init__.py
- wscript
This PR prepares the tree for releasing 3.0.2.
I have also prepared a Github release at https://github.com/projecthamster/hamster/releases/tag/untagged-2bddf81f5958c6731369. Once this PR is merged, publishing that release will create the tag and finalize the release.
See #608 for some more considerations about preparing this release.
> Release 3.0.2

- README.md
> Add package status and installation info

- help/C/keys.page
- src/hamster-service.py
- src/hamster/client.py
- src/hamster/overview.py
- src/hamster/storage/storage.py
This allows toggling the tracking of an activity on and off with
Ctl-Space, as requested in #595.
> Resume last activity using Ctl-Space.

- data/report_template.html
> read 'checked' status correctly and clean up variable names and dead code

- src/hamster/lib/datetime.py
While triaging your project, our bug fixing tool generated the following message(s)-
> In file: [datetime.py](https://github.com/projecthamster/hamster/blob/master/src/hamster/lib/datetime.py#L57), class: date, there is a special method `__sub__` that raises a NotImplementedError. If a special method supporting a binary operation is not implemented it should return NotImplemented. On the other hand, NotImplementedError should be raised from abstract methods inside user defined base classes to indicate that derived classes should override those methods. iCR suggested that the special method `__sub__` should return NotImplemented instead of raising an exception. An example of how NotImplemented helps the interpreter support a binary operation is here.
- [docs.python.org - …
> Fixed Improper Method Call: Replaced `NotImplementedError`
