projecthamster/hamster

src/hamster-service
src/hamster-windows-service

Currently hamster doesn't work in a python3 environment because of these 2 babies.

In a python3 or mixed environment specifiy the major version to use

---

data/preferences.ui

As per suggestion of @brimlar in issue #206: setting expand to true will make the field to edit tags in the preferences window show up properly.

Expand tags field in "Categories and Tags"

---

src/hamster/reports.py

When generating HTML reports , hamster incorrectly handled tags.
Such was before the change
so after a change

Incorrect tags in html reports

---

src/hamster/widgets/facttree.py

Sometimes, in the overview window, one wants to go rapidly to the first or to the last entry (especially since the latter is often the current activity).
This small patch fixes this.
(I also fixed some typos in comments along the way, please tell me if this is okay or not!)

Make Home and End keys work in overview

---

README.md

As shown in #221 targeting prefix /usr/local appears to break library imports on various distros. I don't think any other systems that have already been building to /usr/local would break if they changed to /usr
Distro-specific packages can of course build to whatever dir works for them anyway, too.

Updated README's build instructions to avoid lib import error

---

MAINTAINERS

Thanks to @elbenfreund for [giving write access](https://github.com/projecthamster/hamster-gtk/issues/228#issuecomment-440579659) to keep the legacy [projecthamster/hamster](https://github.com/projecthamster/hamster) alive,
until migration to the `hamster-*` rewrite is recommended.

Maintainer change for the legacy projecthamster/hamster

---

src/hamster/overview.py

`overview.py` contained an obsolete shebang line.
There is no `__main__` inside this file.

remove obsolete env line

---

src/hamster/today.py

There's a bug in Hamster.
Hamster version: 1.04-3 (from Arch Linux)
Desktop Environment: i3
Run Hamster and close the Hamster window (e.g. by hitting Escape).
Then call DBus method `org.gnome.Hamster.Toggle`:
```bash
dbus-send --session --dest=org.gnome.Hamster --type=method_call --print-reply /org/gnome/Hamster org.gnome.Hamster.Toggle
```
As docstring says:
https://github.com/projecthamster/hamster/blob/a5bda5a59abfaa7bd98dc525e5e0a404598c6bcd/src/hamster-service#L129-L133
So Hamster window should show on the screen.
Hamster prints to the output:
```pytb
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/hamster/today.py", line 430, in on_toggle_called
self.window.present()
AttributeError: 'NoneType' object has no attribute 'present'
```
So `self.window` is …

Fix Hamster window toggle on dbus method.

---

src/hamster-cli
src/hamster/client.py
src/hamster/lib/__init__.py
src/hamster/lib/stuff.py
src/hamster/reports.py

The first commit (905d83b) was already prepared and used in export.
The next two commits (8b166c4 and 45c5e87) did fix issue #373.
This removes the `ReportWriter.export` function in `reports.py`
that was no longer used in hamster. 
Since it lead to `ValueError: I/O operation on closed file` anyway,
it was removed altogether.

Fix command line export

---

src/hamster-cli
src/hamster/client.py
src/hamster/edit_activity.py
src/hamster/overview.py
src/hamster/reports.py

Fix issues #152 and #232.
Add the `ongoing_days` keyword argument to `client.get_facts`.
Default to 0 so this should not be breaking.
Overview and command-line use ongoing_days=31 to search for
ongoing activities started in the past month.
Show these ongoing activities in reports too,
to help spot these leftovers.

also look for still ongoing activities

---

src/hamster/widgets/activityentry.py

Otherwise the only way to remove the dropdown of suggestions was to hit `ESC`.

hide suggestions on icon click

---

src/hamster/edit_activity.py
src/hamster/lib/__init__.py
src/hamster/lib/graphics.py
src/hamster/lib/stuff.py
src/hamster/overview.py
src/hamster/storage/db.py
src/hamster/widgets/dates.py
src/hamster/widgets/facttree.py
tests/stuff_test.py

Seems to fix issue #381.
The `fact.id` is not modified when the `fact.end_time` changes,
but comparison of facts was based on `fact.id` alone,
and for some reason, this lead python to *not* rebind `self.facts` to the new `facts` after
https://github.com/projecthamster/hamster/blob/843f3638e62beff2f4b0145cdd362bc7b30cb0ee/src/hamster/widgets/facttree.py#L400
=> assigned but not identical. Weird. (further analysis in #381)
Note: `fact.id` is the hamster database id, not the python `id(fact)`.
With this PR, facts comparison is based on the main attributes.
(excluding `id` and `activity_id` attributes that are database implementation details)

base Fact comparison on main attributes

---

src/hamster-cli

Add a total time line at the bottom of the 'hamster list' command.

add total duration in 'hamster list' command

---

src/hamster/reports.py

For compatibility with python < 3.6.
https://docs.python.org/3/whatsnew/3.6.html#pep-498-formatted-string-literals

use .format() instead of f-string

---

src/hamster/widgets/activityentry.py

Otherwise there was
> PyGIWarning: PangoCairo was imported without specifying a version first.
upon 
```bash
src/hamster-cli add
```

add PangoCairo require_version

---

NEWS
src/hamster/overview.py
src/hamster/widgets/facttree.py

Shortcuts (#230)
Arrows to navigate between dates and facts.
The following are tests, and show potential uses.
Left/Right arrow: change dates
With nothing selected
Ctrl-R: do nothing
Ctrl-N: new empty fact
Ctrl-+: new empty fact
Ctrl-Enter or Enter: do nothing
Select one fact
Ctrl-R clone, starting now
Ctrl-N new empty fact
Ctrl-+ clone, starting now
Ctrl-Enter or Enter: edit selected fact
Create a new fact
if not selected
Delete: do nothing
select the fact
Delete: fact deleted
With enough dates to have more facts than can fit in the overview,
to check scrolling,
check that the following keys work also right at the start of overview,
(without having to focus on the FactTree itself)
Up, Down,
Home, End (change selected fact)
Page up, Page down, (just scroll)
With an ongoing fact …

Improve keyboard handling

---

src/hamster/lib/graphics.py
src/hamster/lib/layout.py
src/hamster/overview.py
src/hamster/widgets/activityentry.py
src/hamster/widgets/facttree.py

Fixed by using functions that are labeled "obsolete" in the documentation,
but still the only workaround to [color issues](https://gitlab.gnome.org/GNOME/pygobject/issues/119).
CSS seemed really nice, but it actually was a nightmare for me to migrate to.
Too many gaps to cross in an otherwise well written gtk documentation,
lots of obsolete stuff online,
and the extensive use of pango/cairo in hamster probably did not help.
This is another place where the rewrite (already using CSS)
seems to be the way to go in the long run.
For testers, [GtkInspector](https://blog.gtk.org/2017/04/05/the-gtk-inspector/) is an awesome tool for debugging theme issues:
```bash
GTK_DEBUG=interactive src/hamster-cli
```
Make sure to check out the `Visual` tab and its `Gtk Theme` combo box
(change theme quickly …

Fix dark theme colors

---

src/hamster-service
src/hamster-windows-service

Fix deprecation message: hamster/src/hamster-service:14: PyGIDeprecationWarning: GObject.MainLoop is deprecated; use GLib.MainLoop instead.

Use GLib.MainLoop instead of GObject.MainLoop

---

src/hamster-service
src/hamster-windows-service

Merged #404 too fast. The `gobject` import lines are no longer used.

remove gobject import

---

src/hamster/widgets/facttree.py

The height must be calculated on the fly, 
otherwise multiline labels would still have a single line height.
Solves #274.

Fix multiline description height

---

src/hamster/lib/graphics.py
src/hamster/widgets/facttree.py

Solves  #413, that was actually hidden before #412.
By the way, fixed row height to avoid tag spill-out such as
Also fixed the category color. 
Now it has always a lower contrast, even when the row is selected.
And that works for other themes (tested with dark adwaita).
Under adwaita the new color is within 5% of the old one.
Developer-wise, the margins are defined in variables, instead of hard-coded.
Changing one of these variables value should still give consistent results.

Fix multiline descriptions

---

src/hamster/edit_activity.py

Most often, it is the time that has to be changed (at least for me).
This is especially true when cloning.
This changes the initial selection in the activity entry line
to be the time information.
Selecting the body can be done quickly by pressing `Right arrow` then  `Shift+End`.
Is there a a consensus about this, or do we have to add an option ?

RFC: preselect time instead of activity

---

wscript

The patch from mwilck for opensuse gets bash completion working on my Ubuntu 19.04 too. See https://build.opensuse.org/package/view_file/openSUSE:Factory/hamster-time-tracker/0005-wscript-install-bash-completion-to-usr-share-bash-co.patch?expand=1

wscript: install bash completion to /usr/share

---

src/hamster/widgets/facttree.py

The use of pango.SCALE to set font sizes results in fonts that are too small on high DPI screens (see #312 and #289). This pull request attempts to resolve the issue by only using relative font sizes (i.e. &lt;small&gt; tag) in the fact tree display.

Fix too small fonts on high DPI screens

---

src/hamster/overview.py

This PR adds a stop_tracking button to the header bar of the overview window (#258). It complements the Ctrl-Space keyboard shortcut and does the same thing.
A few other tweaks are proposed: 1) the settings icon is replaced by an open-menu icon, 2) the order of the buttons is reversed to reflect current trends and to be more similar to apps such as yelp.

Add stop_tracking button to header bar

---

src/hamster/edit_activity.py
src/hamster/widgets/activityentry.py

Allow entering description 
either from the activity line or from the description box,
but not both (fix issue #305).
Prevent saving and give warning in case of ambiguity.
In activity line only, "valid" check mark icon to the right
Both in activity line and in description box: ambiguity (which one to use ?),
"error" check mark icon
More information in the icon tooltip (hovering mouse on the icon)
In description box (multiple lines allowed there), 
"valid" check mark icon
When editing an existing fact, the description is now only displayed in its box.

Fix update activity description ambiguity

---

src/hamster/storage/db.py
src/hamster/widgets/facttree.py

Solves #431.
That seems to work fine, but is not entirely satisfying.
Calling `on_mouse_move` from `on_mouse_down` simulates a mouse move before clicking.
It feels a bit like a hack, but it was not easy to bring the common code to another function,
because of the current structure.
As a note for future development (certainly not just before v3.0 !),
since Facttree is a painter only (more details added to inline comments),
we could get rid of `self.hover_day` and `self.hover_fact`,
and use a property `self.hover_index` that would give the index of the hovered fact
into the `self.facts` list.
That property would use a new `self._mouse_y` that would be updated in `on_mouse_move`,
or `on_mouse_down`.
All  `on_mouse_move` would do is updating `self._mouse_y`.
Another `IndexError` is fixed by …

Always update hover_fact

---

src/hamster-cli

This PR attempts to clarify the usage notes printed by `hamster[-cli] -h` which are currently somewhat misleading.
For example, the current help implies that one can specify the start and end times, and even though they would be parsed correctly, the program actually only uses the date part and not the HH:MM part. 
The message about missing start and end times was also misleading (00:00 to 23:59 instead of using preference for start of hamster day, eg. 05:00).

Clarify hamster cli usage notes

---

src/hamster/lib/__init__.py
src/hamster/widgets/facttree.py

Base comparisons on fact elements only (id is ignored now).
The `or` introduced in 9dc0d96a11077ba3cc18f3c9316c5906bc5084ca was too much magic.
With this PR the reasoning about fact equalities is simplified.
`id` equality has now to be checked explicitly.
This is obviously a breaking change with respect to v2.2.1 which introduced fact comparisons
(precisely 3837ddcc1b1ce5c36377ac9b355c6f92cb06dbdc).

clarify Fact comparisons

---

README.md

The waf build will fail without it and the suggested package in the error message (`install "python-devel"`) is not helping.

Add Ubuntu build dependency

---

README.md

Add python3-xdg and python3-dbus.
Refs #459 regarding Debian testing. I also needed python3-dbus on Ubuntu 18.04.

Update Debian based dependencies in README

---

src/hamster/widgets/facttree.py

In the overview, upon selection,
now display completely the last fact,
even if tags or description are present.

scroll till the end of last fact

---

src/hamster/overview.py
src/hamster/widgets/facttree.py

Add tooltips for the buttons on the overview header bar to improve discoverability for first time users (cf. #447)

Add some tooltips for overview buttons

---

data/edit_activity.ui
src/hamster/edit_activity.py
src/hamster/lib/__init__.py
src/hamster/lib/stuff.py
src/hamster/preferences.py
src/hamster/storage/db.py
src/hamster/widgets/__init__.py
src/hamster/widgets/activityentry.py
src/hamster/widgets/dates.py
src/hamster/widgets/tags.py
src/hamster/widgets/timeinput.py
tests/stuff_test.py

This PR is first step towards verbatim entry.
To fix #280 and #423 some changes will be required in db.py (working on it).
Meanwhile, using completion code/widgets that were still around,
this PR brings back separate field entries, 
as well as completion for time, activity, category and tags.
That should fix #301 and #439.
Feedback welcome !
To do:

Separate edit fields

---

src/hamster/edit_activity.py

As discussed elsewhere, the "Add Earlier Activity" dialog should be renamed to "Add activity" because it can be used to enter earlier, current or even future activities. Use lowercase "activity" to be consitent with "Update activity".

Rename input dialog to "Add activity"

---

src/hamster-service
src/hamster/client.py
src/hamster/lib/dbus.py
src/hamster/lib/desktop.py
src/hamster/storage/db.py
src/hamster/storage/storage.py

With this PR database read/write is done verbatim, without any parsing involved.
This makes a clear separation of concerns.
It partially solves #280 and #423,
although that requires renouncing to the quickness of the cmdline input, until #465 is solved.
This change should not affect the existing dbus interface (old functions have been kept).
The new `AddFactVerbatim` is strongly encouraged if the caller has separate fields.
The old `AddFact` will remain so that passing a single string will remain possible,
to be interpreted by `Fact.parse` on the hamster side.
Unsorted (no category) facts are not supported yet (forthcoming PR almost ready).

Verbatim database read/write

---

src/hamster/edit_activity.py

Make the save button active only if the fact entered can be parsed (and thus edited) from the cmdline.
This hopefully answers https://github.com/projecthamster/hamster/pull/461#issuecomment-549302989 favorably, while waiting for #465.
[This is the last commit of #476, which will be closed]

Forbid unparseable facts - take2

---

src/hamster-service

DBus compatibility was lost, as reported by @jmberg in the shell-extension:
https://github.com/projecthamster/hamster-shell-extension/pull/316#issuecomment-564145295
This is a blind tentative to fix it.
(shell extension does not work here, and an earlier attempt to install it in an ubuntu virtualbox failed)

restore AddFact compatibility

---

src/hamster-service

This hopefully fixes #491.
It should be backward compatible with existing workflows,
while allowing to enter start and end times as well, for people interested.
This is the last commits of the experimental branch described in https://github.com/projecthamster/hamster/issues/491#issuecomment-564730079, rebased on `master`.

bypass (0) and override to None (-1) start/end in DBus AddFact

---

src/hamster/storage/db.py

This fixes a tiny bug in concerning tag autocomplete flags (1 vs. 'true') in the sqlite database, fixed here by checking for not 'false'. See #238.

fix bug preventing removal of autocompletion tags

---

README.md

As adequately noted in https://github.com/projecthamster/hamster/issues/418#issuecomment-567891068, the installation instructions are not clear enough.
@tchama Is [this proposition](https://github.com/projecthamster/hamster/blob/98b8de3a92ad72b1d5f4aab395bfc5db77b9e405/README.md) better ? Thanks for helping ironing out the installations instructions.

Streamline installation instructions

---

src/hamster/lib/configuration.py

Fixed
```
> python3 tests/stuff_test.py 
/home/ederag/share/prog/python/hamster/src/hamster/lib/configuration.py:203: 
PyGIDeprecationWarning:
Using positional arguments with the GObject constructor has been deprecated. 
Please specify keyword(s) for "schema" or use a class specific constructor. 
See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
self._settings = gio.Settings('org.gnome.Hamster')
```

Explicit schema_id in gio.Settings init

---

src/hamster-cli.py
src/hamster-service.py
src/hamster/client.py
src/hamster/edit_activity.py
src/hamster/lib/dbus.py
src/hamster/lib/fact.py
src/hamster/storage/db.py
src/hamster/storage/storage.py

As promised in #482:
> **Breaking change**:
double comma `,,` is now always required to start a description.
Single comma does not work any longer for this purpose.
If a single comma happens to be used by mistake, 
the comma and the following text would end in the category.
So comma will be forbidden in the category,
to raise an error instead of merging a wrong fact in the database.
That will be the purpose of a forthcoming PR.
The same `Fact.check` is used from the command line and from the gui.

check fact before inclusion

---

src/hamster-cli.py
src/hamster-service.py
src/hamster/__init__.py
src/hamster/client.py
src/hamster/edit_activity.py
src/hamster/lib/charting.py
src/hamster/lib/configuration.py
src/hamster/lib/datetime.py
src/hamster/lib/dbus.py
src/hamster/lib/fact.py
src/hamster/lib/graphics.py
src/hamster/lib/layout.py
src/hamster/lib/parsing.py
src/hamster/lib/pytweener.py
src/hamster/lib/stuff.py
src/hamster/overview.py
src/hamster/preferences.py
src/hamster/reports.py
src/hamster/storage/db.py
src/hamster/storage/storage.py
src/hamster/widgets/__init__.py
src/hamster/widgets/activityentry.py
src/hamster/widgets/dates.py
src/hamster/widgets/dayline.py
src/hamster/widgets/facttree.py
src/hamster/widgets/timeinput.py
tests/stuff_test.py

Introduce `hamster/lib/datetime.py`.
This is the first step towards fixing #166.
For now times are still "naive", 
but this PR should allow us to smoothly shift to "timezone-aware" later on.
We also now have full control on the python/sql conversions
(does not change anything yet, but creates opportunities).
Bonus: code seems a bit clearer with parsers close to their objects.
The ephemeral `parsing.py` will soon be removed.
Some `stuff.py` code was transferred to the new `datetime.py`, but compatibility is retained for a while.
Transfer can be finished later.

Hamster datetime

---

src/hamster-service.py
src/hamster/client.py
src/hamster/lib/datetime.py
src/hamster/lib/dbus.py
src/hamster/storage/db.py
src/hamster/storage/storage.py
tests/stuff_test.py

The custom fact signature used in the past was hard to extend.
For instance timezone info addition would require a signature change.
Hence pass verbatim fact as a string in [json](https://docs.python.org/3.7/library/json.html) format.
Better change that now while no-one else uses the verbatim interface introduced in #466, 
about 3 months ago.
The replacement D-Bus method `GetFactsJSON` first argument is a range string,
same syntax/parser as the command line. 
This parser understands a single hamster day, a day range, or a precise datetimes range.
This PR is fully backward compatible for the [hamster-shell-extension](https://github.com/projecthamster/hamster-shell-extension),
since that uses `GetTodaysFacts` and `AddFact`, not `AddFactVerbatim`.
Added `GetFactJSON` and `GetTodaysFactsJSON` …

json verbatim

---

data/wscript_build

`appdata` is [deprecated](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#sect-Metadata-GenericComponent).

Install metainfo.xml in metainfo

---

src/hamster/lib/datetime.py
tests/stuff_test.py

Should return a `hday`, obviously.
It was sometimes returning a date, due to the timedelta subtraction.

Fix hday.today() type

---

src/hamster-cli.py
src/hamster/lib/configuration.py
src/hamster/overview.py

For early testing:
Migrate to [Gtk.Application](http://lazka.github.io/pgi-docs/Gtk-3.0/classes/Application.html).
This is at least a first step towards #242.
Note: the Gtk.Application is run only when a window is actually requested,
otherwise `hamster-cli.py` remains a standard python script.
By the way, fixed #283.

Migrate to Gtk.Application

---

src/hamster-service.py
src/hamster/storage/db.py

Cleanup: returned `id` is always an `int`, never `None`.

return id = 0 upon failure

---

src/hamster/edit_activity.py
src/hamster/lib/datetime.py
src/hamster/lib/fact.py
src/hamster/lib/parsing.py
src/hamster/widgets/activityentry.py
tests/stuff_test.py

This started as a fix to the following behavior:
to enter `-10 activity`, while typing, 
`-10` was interpreted as an activity, until the `a` was typed, 
and only then `-10` was interpreted as a start.
Now `-10` is interpreted as a start right after `1` is typed.
*Note: There is no way to know what the user has in mind until the second character is typed, 
so at first `-` appears in the activity, which is fine actually (tried to swallow it, worse down the line)*
Then, since parser was touched, it became irresistible to add the possibility for positive
relative times, entered as `+nnn` (plus sign followed by 1 to 3 digits).
Signed relative times (e.g.  `-10`or `+10`) are always relative to reference (normally, `now`).
Finally my preferred one; end time can be replaced with the fact duration …

Richer relative times

---

src/hamster/edit_activity.py
src/hamster/widgets/activityentry.py
src/hamster/widgets/timeinput.py

Fix #339.
The `gdk.WindowTypeHint.COMBO` and `set_attached_to` lines 
do not do much, but seem right.

Fix wayland popup positions

---

src/hamster/storage/db.py

Otherwise it might pick an unused `hamster-applet/hamster.db` 
(for some reasons it was not hard linked on my system
*Edit: that was due to file synchronization by unison*)
instead of the more recent `hamster-time-tracker/hamster.db`.
The change to hamster-time-tracker has never been released, 
but it is few months old (9f345e5eac477bba5d4f3ea68d71aa21cc39e3b1), 
so it is nicer to early adopters to handle that correctly as well.
Check for hard links (the first numbers should be identical):
```bash
ls -il ~/.local/share/hamster*/hamster.db
1105569312 -rw-rw-r-- 3 ederag users 1589248  7 déc.  09:50 /home/ederag/.local/share/hamster-applet/hamster.db
1105569312 -rw-rw-r-- 3 ederag users 1589248  7 déc.  09:50 /home/ederag/.local/share/hamster-time-tracker/hamster.db
1105569312 -rw-rw-r-- 3 …
```

Link from most recent database directory first

---

wscript

Bash loads completion scripts from 2 directories:
*   $(syscondir)/bash_completion.d/
*   $(datadir)/bash-completion/completions/
The former is meant to be used by local administrators to drop their own
files in, and the latter is what software installers should use.
In the past Hamster used to install its completion file in the former,
but this was changed with 1d562615a5e5e2c97be3aa379c4dea3709f26f04.
Unfortunately that commit had a typo and the last "s" was missing from
the path.
This commit fixes that typo.

build: Install the Bash completion file in the right place

---

data/wscript_build

Not having this makes it a bit harder to launch the app. :stuck_out_tongue_winking_eye:

build: Install the desktop file

---

org.gnome.hamster.Windows.service.in
org.gnome.hamster.service.in
wscript

This is the proper directory according to the GNU guidelines:
> The directory for installing executable programs to be run by other
> programs rather than by users.
https://www.gnu.org/prep/standards/html_node/Directory-Variables.html#index-libexecdir
Libexecdir used to be absent from the FHS but it was added in version
3.0 of the standard, which was released in 2015:
> /usr/libexec includes internal binaries that are not intended to be
> executed directly by users or shell scripts. Applications may use a
> single subdirectory under /usr/libexec.
https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html#usrlibexec
Those executables are the launchers for the background services, and are
not intended to be run by users (e.g the Linux one is run by DBus) which
makes libexecdir the better …

Install the service executables in libexecdir

---

src/hamster/client.py
src/hamster/storage/db.py

```
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.sqlite3.OperationalError:
Traceback (most recent call last):
File "/home/sh_zam/workspace/hamster/src/hamster/storage/db.py", line 844, in __remove_index
self.execute("DELETE FROM fact_index where id in (%s)" % ids)
File "/home/sh_zam/workspace/hamster/src/hamster/storage/db.py", line 939, in execute
cur.execute(state, param)
sqlite3.OperationalError: near "(": syntax error``

Fix crash when editing or deleting an activity from overview

---

src/hamster/lib/datetime.py
src/hamster/lib/stuff.py
tests/stuff_test.py

`timedelta.total_minutes()` will replace `format_duration` in v4.0.

Add timedelta.total_minutes()

---

src/hamster/storage/db.py

In older versions of the database one can find milliseconds in
timestamps of facts-table. When loading, one gets a ValueError exception.
Fix this by adding a default microsecond.

Add backward compatibility of timestamps of facts-table

---

data/edit_activity.ui
src/hamster/edit_activity.py
src/hamster/widgets/activityentry.py

- Numpad Enter was doing nothing in the gui cmdline entry.
- 926ca6bb9fa369a5c90e67fd85b3be4d3aabace4: cleaner, and moreover,
updates the entry content prior to showing the suggestions. Fixes the following bug:
> new activity
click on start time, select a time
click on the cmdline dropdown icon,
select a completion; the text is changed but not the fields
- 5331e84a004d2a40c4b45ef666db0f15f5153d82
add "cmdline" label
(bug reports were confusing, cf. #515)
By the way, change to a GtkBox (why an alignment ?)

cmdline gui small improvements

---

README.md

At least Ubuntu 19.10 needs it for glib-genmarshal to be available

Add libglib2.0-dev-bin Ubuntu dependency

---

src/hamster/widgets/activityentry.py

Because `key` was being returned in lowercase, matching would fail.

Fix completion in categories TreeView

---

src/hamster-cli.py

Under wayland, passing application_id to Gtk.Application.Init()
is not sufficient to set the application ID and program name
so that the shell sees it. See e.g.
https://www.programcreek.com/python/example/87806/gi.repository.GLib.set_prgname
https://gitlab.gnome.org/GNOME/gtk/issues/653
https://gitlab.gnome.org/GNOME/gtk/commit/72ec8963d7df0e39f688838e42445c869e4875c9
This should fix #541.

hamster: explicitly set application ID and prgname on startup

---

src/hamster-service.py

This is #491 again,  supplemented with "if the parsed fact has no start, use now".
Should be better than #492, 
fix #560 while keeping full backward compatibility with existing clients.
@jmberg the `10:00 meeting` activity can be entered either by tricking
(e.g. prepending a character: `.10:00 meeting`),
or (that's new) by using double dashes `--` as explicit missing times (see help).
Here That would be `-- -- 10:00 meeting`.
@mwilck Thanks for your test case in #491. Now the time would not be ignored,
so in some sense #492 was not, while this one is fully backward compatible.
If a client wants "activity without range" (*not recommended at all*), 
it could just prepend `-- -- ` to the string:

No start override

---

README.md
help/Makefile.am
help/wscript

xml2po is deprecated and itstool from Yelp is recommended as its
replacement.
The code in wscript that handles this looks at the Makefile.am file to
figure out what pages and languages to compile. The Makefile is not
actually executed in this process, but is presumably present to allow
manually compiling the helpfiles too. This makefile is adapted to the
style used by itstool, changing DOC_ variables to HELP_ variables.
This also moves legal.xml from DOC_INCLUDES to HELP_PAGES, to make sure
it is still processed. At the same time, the python code is modified to
also process .xml files (instead of just .page files). Note that before
this commit, legal.xml would be processed by the Makefile, but not by
the wscript file, which is now fixed.
Whereas xml2po (when run with -p) would combine an …

Use itstool instead of xml2po

---

src/hamster/lib/datetime.py
tests/stuff_test.py

Fix handling of datetime arguments to from_start_end

---

src/hamster/widgets/facttree.py

While migrating to Ubuntu 20.04 from 16.04 I noticed that the current version of Hamster doesn't provide daily totals in the Overview screen. This PR introduces a "Total" row after each day. These rows can't be selected (clicked) and navigation with the cursor keys skip them. These rows are not included when exporting the tasks.
Here you can find a screenshot of how the modifications look like: https://ibb.co/GFPv2Sj
Please note that I'm not really familiar with Python, so please let me know if there is something in my changes that can be improved.

Daily summary totals added to Overview screen

---

.github/workflows/testing.yml
README.md
org.gnome.Hamster.json

This PR adds flatpak support for Hamster. Building the application is surprisingly easy, and making it available on flathub should contribute to Hamster's usage growth.

Add a flatpak manifest

---

data/org.gnome.Hamster.GUI.metainfo.xml

User *bigon* reported: "It looks like the appstream file is not pointing
to the png of the screenshots directly but to an html page" and provided
the links in this PR.
Fixes #641.

Fix links to screenshots in appstream file

---

src/hamster/widgets/facttree.py

The overview currently has dark bars for days with no recorded facts. These are considered unsightly by some (eg. #615, and me too). The behaviour is inconsistent because empty days at the start and end of the date range are not highlighted whereas intermediate empty days are.
This PR completely skips over empty days in the selected date range.
(This is a revival of #619, already approved by mwilk. I promise to be more patient this time.)

Remove dark bars for empty days in overview (take 2)

---

data/date_range.ui
src/hamster/widgets/dates.py

This simplifies the Rangepick widget by using `gtk.Popover` and `gtk.MenuButton`, conveniently handle a lot of the boilerplate of hiding and showing the popup automatically. This also allows removing some problematic code, fixing #639 and because no separate window is created anymore, this indirectly also fixes #645.
This slightly changes the looks of the popup, previously it was:
Now it is:
Note the "arrow", border and slightly different positioning of the popup.
One downside of using a Popover is that it is a widget, rather than an window, so at least on X11, it cannot extend outside of the containing window, but this is probably not a problem in practice (this limitation does not seem to exist on Wayland, see https://gitlab.gnome.org/GNOME/gtk/-/issues/543).
This PR supersedes #643 and …

Simplify Rangepick widget to fix issues on Debian Buster

---

src/hamster/overview.py
src/hamster/widgets/facttree.py

Right now FactTree.set_facts() is always resetting the position of the
view, bringing the user back to the top but this function is called
regularly to update with the latest data even when the user has not
changed anything in the selection widget... which is really annoying
when you are reviewing the list of facts.
Let's distinguish between both cases with a "reset=True" attribute that
we use when we generate an entirely new set of facts to be displayed.
This makes #623 obsolete. Thanks to @mwilck for the initial analysis.
Fixes #594

Reset position in FactTree only when needed

---

data/org.gnome.Hamster.GUI.desktop.in

The Debian package checker, lintian, complains about the .desktop file
missing a "keyword" entry.
Fixes #629

Add keyword entry to .desktop file

---

src/hamster/edit_activity.py
src/hamster/preferences.py
src/hamster/widgets/activityentry.py
src/hamster/widgets/tags.py
src/hamster/widgets/timeinput.py

Similar to other recent wayland popup issues.
Without setting parent the tag popup opens and immediately closes. Previously it only meant that popup doesn't stay opened, but recently it started interfering with focus making it difficult to type in text.
Tested on ArchLinux with GTK 3.24, Gnome desktop and wayland.

Fix tag popup displaying by setting parent.

---

README.md

The documentation for the edited section is missing the unzip command and gets the name of the output file wrong. This fixes both.

Fix documentation in Download & Unzip section

---

src/hamster/storage/storage.py

Please accept this PR into the next hamster release.
It enables the xfce4-panel-plugin to do in-place edits without adding a json library dependency.
Original author is @ederag .

#671: convert str to Fact before check

---

src/hamster/edit_activity.py

This is another fix for the calendar picker issue #590, that intends to be a minimal fix for just that issue (so it's easy to review), without introducing any side effects.
I've tested this in various circumstances (new/existing facts, start/end times before and after midnight, changing the date using the dayline and the date pickers) and it seems to hold up well enough. I did not some usability issues (you cannot set an end date if there is no end time, if you remove the start time, the dayline buttons stop working), but all of those already existed before this change, so I'll leave those for a later PR.
The commit message is below and should explain how this fix works (and is longer than the diff :-p):
Previously, setting the `date` property would (in addition to setting
the property …

FactController: Fix start date picker modifying date twice

---

src/hamster/widgets/facttree.py

Fixes #698. The width alotted to the time interval in the overview was
fixed at 100 pixels but that was not sufficient when using large/wide
fonts. This PR uses the pixel width of ""00:00 - 00:00" when rendered
using the current default font.

Fix time-activity overlap with wide fonts

---

src/hamster/lib/i18n.py

This function was deprecated and eventually removed in Python3.11 (see changelog at https://docs.python.org/3/whatsnew/3.11.html)
> Removed the deprecated gettext functions lgettext(), ldgettext(),
> lngettext() and ldngettext(). Also removed the bind_textdomain_codeset()
> function, the NullTranslations.output_charset() and
> NullTranslations.set_output_charset() methods, and the codeset parameter
> of translation() and install(), since they are only used for the
> l*gettext() functions. (Contributed by Dong-hee Na and Serhiy Storchaka
> in bpo-44235.)
Fixes #714

Remove call to deprecated bind_textdomain_codeset gettext function

---

.github/workflows/testing.yml
src/hamster/lib/pytweener.py

This fixes the flake8 workflow (which failed due to missing python 3.5 on ubuntu-latest) and fixes the test suite on python3.5 (due to no longer supported explicitly configured ubuntu-18.04). See commit messages for a bit more details.
Note that that with this change, we could also consider lowering the required python version from 3.6 back to 3.5 (it was only raised by @tchernobog in #685 in the assumption that ubuntu-18.04 did not have 3.5, but looking at the [python-versions](https://github.com/actions/python-versions/blob/main/versions-manifest.json) repo, which is used by the [setup-python action](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#available-versions-of-python-and-pypy), I believe it *is* actually available), but since python 3.6 is pretty well …

Use ubuntu 20.04 for workflows

---

README.md

Following https://github.com/projecthamster/hamster/issues/688

Update Flatpak installation instructions

---

src/hamster/reports.py

Having any html/xml characters in the description breaks the reports output in html (surely in xml as well, have only tested html).

Bug Fix: Escape html characters for XML/HTML reports

---

.github/workflows/testing.yml
README.md

(Should also be added to the packaging system, but I don't know how that works.)

Add python3-gi-cairo as a dependency in the README

---

help/C/input.page
src/hamster/lib/fact.py
src/hamster/lib/parsing.py
tests/test_stuff.py

This PR builds on top #662 to further simplify the parsing facts by creating a clear barrier between the description and the tags. But to be nice with the user, we support a subset of tags within the description that we copy over to the tag list and that we keep as plain words within the description.

Simplify parsing of facts with a clear tag barrier

---

.github/workflows/testing.yml
org.gnome.Hamster.yml

The previously used version 41 has been unsupported since 2022, so update it.
This does not update dbus-python yet, since the 1.3.0 version requires meson as a build system, but seems to require a newer version than what the gnome/freedesktop 45 SDK supports and manually installing a newer version takes more effort with no signficant gains, see also https://github.com/flathub/net.lutris.Lutris/blob/7bd51222b8076abd8fcbfe9cb0e4d6e70bafca24/net.lutris.Lutris.yml#L775-L780

flatpak: Update gnome platform

---

NEWS.md
README.md
src/hamster/VERSION

These are the final changes to release 3.0.3.
The release procedure, as proposed in https://github.com/projecthamster/hamster/issues/686#issuecomment-1817470671 is as follows:
1. Document all changes in the `NEWS.md` file
2. Make a commit that sets the version number in `src/hamster/VERSION` and version number and release date in `NEWS.md`
3. Tag that commit (or the merge commit if merged through a PR)
4. Create a github release with the notes from the NEWS file, and attach the flatpak build.
5. Create a new commit that removes the version number again and adds a `## Unreleased changes` header to `NEWS.md` and reset `src/hamster/VERSION` to `unreleased`.
This PR handles 1. and 2. I already have a commit locally for 5. I plan to do merge this PR and do 3. and 4. tonight.
If there's anyone …

Release 3.0.3
